name: namer_app
description: A simple to-do list app in Flutter

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.1
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: "^3.4.0"

flutter:
  uses-material-design: true
